site_name: Azure DevOps Java SDK
site_url: https://example.com/
site_description: Documentation portal for azure devops java sdk (azd)
site_author: Harish Karthic

nav:
  - Home: index.md
  - Docs:
    - 'Quick Start': 'docs/quickstart.md'
    - 'Accounts': 'docs/accounts.md'
    - 'Build': 'docs/build.md'
    - 'Core': 'docs/core.md'
    - 'Distributed Task': 'docs/distributed-task.md'
    - 'Extension Management': 'docs/extension-management.md'
    - 'Feed Management': 'docs/feed-management.md'
    - 'Git': 'docs/git.md'
    - 'Graph': 'docs/graph.md'
    - 'Member Entitlement Management': 'docs/member-entitlement-management.md'
    - 'Pipelines': 'docs/pipelines.md'
    - 'OAuth': 'docs/oauth.md'
    - 'Policy': 'docs/policy.md'
    - 'Release': 'docs/release.md'
    - 'Service Endpoint': 'docs/service-endpoint.md'
    - 'Service Hooks': 'docs/service-hooks.md'
    - 'Wiki': 'docs/wiki.md'
    - 'Work': 'docs/work.md'
    - 'Workitem Tracking': 'docs/workitem-tracking.md'
  - About:
    - 'Release Notes': 'about/release-notes.md'
    - 'License': 'about/license.md'
    - 'Contributing': 'about/contributing.md'

markdown_extensions:
    - toc:
        permalink: "#"
    - admonition
    - attr_list
    - def_list

theme: 
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - django
